### ISSUE TITLE
DeploymentConfig defaults to 0 replicas, should be 1

### ISSUE THREAD

**Issue by containscafeine** [kedgeproject/kedge#359] opened 2017-10-13 12:06 UTC
Specifying no replicas in DeploymentConfig results in 0 replicas. It should be 1, like in case of Kubernetes.

```yaml
controller: deploymentconfig
name: httpd
containers:
- image: centos/httpd
services:
- name: httpd
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
```

Similar discussion in https://github.com/kedgeproject/kedge/pull/315#discussion_r143998519

**Comment by kadel** [comment] 2017-10-13 12:17
duplicate of https://github.com/kedgeproject/kedge/issues/357

**Closed** 2017-10-13 13:46 UTC
Labels: kind/bug
