### ISSUE TITLE
Hard-code API details / what versions of Kubernetes to point to

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#434] opened 2017-11-07 16:44 UTC
For example:

```sh
kedge --kubernetes-version 1.7
```

Will output a "deployment" file based on v1, however, previous versions (ex. 1.4 Kubernetes) will deploy as `kind: extensions/v1beta1`.

Hard-coding the file will help companies / users deploy to Kubernetes efficient by:

```sh
 kedge generate --kubernetes-version 1.7 -f gitlab.yaml -f redis.yaml -f postgres.yaml | kubectl create -f - 
```

**Comment by containscafeine** [comment] 2017-11-08 10:02
Duplicate of #141

**Closed by containscafeine** 2017-11-08 10:02 UTC
