### ISSUE TITLE
Command line test (similar to kompose)

### ISSUE THREAD

**Issue by surajnarwade** [kedgeproject/kedge#495] opened 2017-11-28 06:55 UTC
we should have command line tests like kompose, https://github.com/kubernetes/kompose/tree/master/script/test in kedge.

**Comment by surajssd** [comment] 2017-11-28 12:40
This is duplicate of https://github.com/kedgeproject/kedge/issues/58

**Comment by kadel** [comment] 2017-11-28 13:20
closing as duplicate

**Closed by kadel** 2017-11-28 13:20 UTC
Labels: kind/tests, priority/medium, size/XL
